### ISSUE TITLE
Automatic mode for parser

### ISSUE THREAD

**Issue by sushant94** [radare/esil-rs#1]
Though the current ESIL parser is good and convenient to use compared to raw esil, there are a few improvements that I'd like to add that would make it easier to use.

- Automate setting of `old`, `cur` and `lastsz` in the parser. These are non-intuitive and easy to forget or not do correctly. Of course this feature could be disabled in applications where this is not suitable, but for most cases this would work fine. Also add a warning to warn the user when `old`, `cur` and `lastsz` were not updated correctly as per the ESIL semantics.

**Comment by sushant94** [comment]
- Implemented in 10d7b67e8668b07ab75201da2cdb4ae49b6d3891
- Future improvement: Set old, cur and new automatically based on pushed stack values. Option to disable this feature. Warn the user when cur, old and lastsz have not been set correctly.

**Comment by radare** [comment]
I would prefer for simplicity and just not have this thijg configurable.

Also, we need an rreg implementation in rust.. Or at least a wrapped library on top if r_reg. This is necessary for proper register use otherwise how do u track register usage?

**Comment by sushant94** [comment]
> I would prefer for simplicity and just not have this thijg configurable.

By config, I mean a simple argument to the parser::new() in order to disable this.

> Also, we need an rreg implementation in rust.. Or at least a wrapped library on top if r_reg. This is necessary for proper register use otherwise how do u track register usage?

This is specific to the project currently. This is related to issue #5 . I think it would be a good idea to define consistent traits to implement register profile and memory profile and leave the implementation to be application specific. We could write one for the VM by parsing the output for register profile from radare2. Maybe we can discuss more about this on #5.

**Comment by sushant94** [comment]
Done in f643b19d5b91e9de0d1e2e2dacf0105c9dbba186
