### ISSUE TITLE
Link to radare2 docs is broken

### ISSUE THREAD

**Issue by SnirBroshi** [radare/esil-rs#21]
The link to radare2 docs of ESIL is broken, they've moved the `disassembling` folder in a `src` folder,
so the new link is `https://github.com/radareorg/radare2book/blob/master/src/disassembling/esil.md`

**Comment by trufae** [comment]
You can edit the page directly using the pencil button. That will create the PR

**Comment by SnirBroshi** [comment]
@trufae I got the impression that this project is abandoned, so I just left an issue in case the maintainer comes back

but sure I added a PR

**Comment by trufae** [comment]
everything is abandoned until someone commits. thanks for the PR!
